dependencies:
- name: "prometheus"
  version: "8.3.0"
  repository: "@stable"

- name: "grafana"
  version: "1.24.1"
  repository: "@stable"

- name: "loki"
  version: "0.0.1"
  repository: "file://loki"
